Make sure node_modules exists so that db migration can be performed
Resolves this error:
Reading config file '/app/drizzle.config.ts'
Error please install required packages: 'drizzle-orm'
error: script db:push exited with code 1
Database schema changes failed. Check logs with 'docker compose logs'.